#!/usr/bin/env python3
"""One-command sync of *derived* artifacts after editing the machine source.

Regenerates the human view (a true derivation — it is re-rendered), then
re-runs the gate. The prototype manifest hash is NOT refreshed by default:
the prototype is not regenerated by this command, so silently re-stamping it
would turn "freshness proof" into a side effect of running sync. Pass
--attest-prototype only after a human/agent has actually re-verified the
prototype against the new machine content.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from .generate_human import main as generate_human_main
from .libproto import expected_manifest_path
from .libspec import (
    expected_human_path,
    load_project_for,
    load_spec,
    spec_hash,
    validate,
)

USAGE = "Usage: specnotary sync <machine-spec.yaml|json> [--attest-prototype]"
_HASH_LINE = re.compile(r"^(\s*hash:\s*).+$", re.MULTILINE)


def _refresh_manifest_hash(manifest_path: Path, digest: str) -> bool:
    text = manifest_path.read_text(encoding="utf-8")
    new_text, n = _HASH_LINE.subn(rf"\g<1>{digest}", text, count=1)
    if n == 0:
        return False
    if new_text != text:
        manifest_path.write_text(new_text, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    attest = "--attest-prototype" in argv
    argv = [a for a in argv if a != "--attest-prototype"]
    if len(argv) != 1:
        print(USAGE)
        return 2
    src = Path(argv[0])
    if not src.exists():
        print(f"FAIL: file not found: {src}")
        return 2
    try:
        data = load_spec(src)
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL: {exc}")
        return 4 if "PyYAML" in str(exc) else 2
    if not isinstance(data, dict):
        print("FAIL: root must be object")
        return 1

    project = load_project_for(src)
    if isinstance(data.get("project_hint"), dict):
        project = {**project, **data["project_hint"]}

    machine_only = validate(data, project, spec_path=src, check_human=False)
    machine_fails = [e for e in machine_only["fail"] if not e.startswith("prototype")]
    if machine_fails:
        print("FAIL: machine spec has FAIL items — fix before sync")
        for e in machine_fails:
            print(f"FAIL: {e}")
        return 1

    digest = spec_hash(data)

    manifest = expected_manifest_path(src)
    if manifest is not None and manifest.is_file():
        if attest:
            if _refresh_manifest_hash(manifest, digest):
                print(f"attested: {manifest} (generated_from_spec.hash refreshed)")
                print("NOTE: attestation means a human/agent re-verified the prototype against the new machine content")
            else:
                print(f"WARN: no hash line found in {manifest} — update manually")
        else:
            print("NOTE: prototype hash NOT refreshed — sync does not regenerate the prototype.")
            print("      Re-verify the prototype, then run: specnotary sync <spec> --attest-prototype")

    human = expected_human_path(src)
    if human is None:
        print("FAIL: cannot resolve human path (machine file not under machine/)")
        return 1
    gen_args = [str(src), str(human)]
    if human.is_file():
        # Preserve the language the human view was generated with.
        from .libspec import parse_human_header  # noqa: PLC0415

        lang = (parse_human_header(human.read_text(encoding="utf-8")).get("lang") or "zh").strip()
        if lang and lang != "zh":
            gen_args += ["--lang", lang]
    rc = generate_human_main(gen_args)
    if rc != 0:
        return rc

    result = validate(
        data,
        project,
        spec_path=src,
        human_path=human if human.is_file() else None,
        manifest_path=manifest if manifest is not None and manifest.is_file() else None,
    )
    print(f"FAIL_COUNT: {len(result['fail'])}")
    print(f"WARN_COUNT: {len(result['warn'])}")
    for e in result["fail"]:
        print(f"FAIL: {e}")
    for w in result["warn"]:
        print(f"WARN: {w}")
    print("RESULT: FAIL" if result["fail"] else "RESULT: PASS")
    return 1 if result["fail"] else 0


if __name__ == "__main__":
    sys.exit(main())
